spring.application.name=job-application-tracker
server.port=8000
logging.level.root=INFO

# Enable H2 Web Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# DB Connection Settings
spring.datasource.url=jdbc:h2:mem:mydb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Hibernate properties
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

